name: Build SBOM and send to dt-api
on: push
jobs:
  my Job:
    runs-on: ubuntu-latest
    steps:
      - name: Cryptosoft-SBOM-DT
      uses: CryptosoftInc/Dependency-Track@1.0.0
      with:
        dt-url: "https://dt-api.staging.cryptosoft.com"
        api-key: "odt_YHhY91Mr_t9s4StqeqX87Dc1YcgtRncr85oMN3q0r"
        project-name: ""
        project-version: "1.0.0"
